language: node_js
node_js:
  - "node"
env:
  - HUSKY=0
  - CODECOV_TOKEN="b754ec8a-0cb3-4958-8d7c-8cca5190f53c"
cache:
  directories:
    - node_modules
before_install:
  - pip install --user codecov
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - codecov --file coverage/lcov.info --disable search
