language: node_js
node_js:
  - "node"
addons:
  sonarcloud:
    organization: michaeldzjap-github
env:
  - HUSKY=0
cache:
  directories:
    - node_modules
before_install:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
before_script:
  - npm run lint
script:
  - npm test
  - sonar-scanner
after_success:
  - ./codecov -f coverage/lcov.info
